// content for docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: postgres
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
